### ISSUE TITLE
cis_3_3_3 fails to stop / disable ip6tables

### ISSUE THREAD

**Issue by canihavethisone** [fervidus/secure_linux_cis#10]
the resource declaration on line 36 of 'services' should be 'service' and fails to compile a catalog when ipv6_enabled => false, however when corrected results in duplicate resource declaration with puppetlabs/firewall.

A way to overcome this is to set in hiera:
 `firewall::ensure_v6: 'stopped'`
 however there needs to be a method determined how to do this in the manifest.

I am trying resource collectors etc but as yet not have a way to stop/disable ip6tables from the firewall dependency.  Overriding a default in a dependency is not as easy as it could be.

**Comment by dan-wittenberg** [comment]
Makes sense and wonder how that made it past all the testing...hmmmm

**Comment by canihavethisone** [comment]
Agreed.  It should have failed to compile.  My testing method is manual at this stage as I can't get spec or acceptance tests to work with this module.  Not sure if it's how PDK is structured in the current version.

As mentioned, I am fighting with overriding defaults in dependent modules.  I think Puppet need to make this easier, particularly where subclasses as declared in parent classes of dependencies.  Using hiera is easy, but not applicable when we are essentially creating 'wrappers' for dependencies.  I guess some major ruby foo may do it, but it shouldn't be that involved.

**Comment by dan-wittenberg** [comment]
I removed the service definition, and tested with the kernel param along
with the sysctl and saw an error about trying to startup at boot, but that
seems worth it to deal with, you can just stop the service if you really
want.  I also didn't see any deps errors with the other manifests since
ipv4 is still enabled, so I'm inclined to just ignore the service error
since it doesn't break anything, it's annoying and can be removed by the
user by whatever means they are managing.  Any other issues around ipv6?

**Comment by dan-wittenberg** [comment]
I am also curious why there's yet another ipv6 enable/disable option, that
basically seems to duplicate the "enforced" option, and I'm voting to
remove that completely and just say if you want to stop it from disabling
ipv6 just enforced=false for those.  Any objections?

**Comment by canihavethisone** [comment]
I'm looking into this today.  I have previously found that when the kernel param is used to disable ipv6, puppetlabs/firewall has an issue unless $ip6tables = 'stopped' or disabled.

**Comment by dan-wittenberg** [comment]
That sounds like a reasonable solution then, so we could still disable in
the kernel per cis suggestions.

Dan

**Comment by bryanjbelanger** [comment]
No objections.

**Comment by canihavethisone** [comment]
so I have some progress with a resource collector, not yet got it perfect.  The blow example disables bot ip6tables and iptables....nearly there I think.
`    Service <| tag == 'firewall::linux::redhat' |>
      {
        ensure => stopped,
        enable => false,
      }`

**Comment by canihavethisone** [comment]
ok I think I have got this one.  there entire 3_3_3 manifest should be as below.  I removed the sysctl resources a they fail after a reboot when the kernel_parameter is set.  Also, this and I'm sure other changes to the host require a reboot to take effect.  Should use of the puppetlabs-reboot module be considered and notify entries created on classes that need create changes requiring a reboot?

I will do a final round of testing over the next 2 hours.  Who wants to merge this change once I have confirmed it is solid?

class secure_linux_cis::redhat7::cis_3_3_3 (
  Boolean $enforced = true,
  Boolean $ipv6_enabled = true,
) {

  if $enforced and !$ipv6_enabled {

    kernel_parameter { 'ipv6.disable=1':
      ensure => present,
    }

    Service <| tag == 'ip6tables' |>
      {
        ensure => stopped,
        enable => false,
      }
  }
}

**Comment by canihavethisone** [comment]
I also think that ipv6_enabled should be set to false in init.pp, as it should be opt-in, not opt-out.

**Comment by dan-wittenberg** [comment]
I would like to remove it, it seems to me that is why we have the enforced
option for.  So this service option only works if it's tagged right?  So if
you are using something other than that one module it would have issues?  I
guess I'm not sure it's a great idea to put a dependency on a module we
have no control over for something that isn't really a dependency if that
makes sense.  It won't break anything if you don't do this, it just
complains right?  Then you can manually turn it off in your own firewall
code and that will go away?  Just trying to make sure I understand the need
for it.

**Comment by canihavethisone** [comment]
As I understand it, the tagging is automatic, not set by puppetlabs-firewall.  Therefore the above solution should work regardless of what other resources or deps are managin ip6tables. 

The reason for needing it is this:  
1. CIS recommend that ipv6 is disabled in the kernel (grub.cfg) unless specifically required.  (therefore also default it to ipv6_enabled = false
2. Puppetlabs-firewall defaults to starting and enabling ip6tables unless overridden in either hiera, or a method such as above in a wrapping class.
3. When the ipv6 is disabled via the kernel, and the ip6tables service tries to start (as it will due to point 2 above), the errors appear as per the current release of this module.

I will try a setting other than tag ==, however I don't think using tag matters as its how it appears in the catalog regardless of how it got there.  

If your concern is 'what if this module stops using puppetlabs firewall and/or any presence of the ip6tables service stops appearing in the catalog', then I suggest the above block gets put in a if statement such as :

        if Service['ip6tables'] {
         Service <| tag == 'ip6tables' |>
          {
            ensure => stopped,
            enable => false,
          }
        }

I have done manual testing on this and it seems a viable solution.

**Comment by dan-wittenberg** [comment]
I think your solution is good, no issues with that, just a concern of
managing something we don't have to. Have you tested in a case where there
is no serice by that name?

Good work I do like it!

**Comment by canihavethisone** [comment]
I think we DO **have** to manage it for the 3 combined points above, (and to default ipv6_enabled to false) but mostly of all due to the way this module interacts with puppetlabs-firewall (which defaults to enabling ip6tables).

The ip6tables service exists by default on RHEL and Centos.  I also tested by actually 'removing' the service by deleting /lib/systemd/system/ip6tables.service file and the 'systemctl daemon-reload'.  The proposed changes to class cis_3_3_3 still fine, though if the service is totally ABSENT (not just stopped/disabled), puppetlabs-firewall throws an error if the proposed changes are absent!  Therefore we start to get into the realm of things that will never happen unless a host is already borked.

I will fork v1.0.10 and add the change above to cis_3_3_3 and also default ipv6_enabled to false in init.pp, then create a pull request

**Comment by canihavethisone** [comment]
so, title == can be used instead of tag ==, and in this module they both seem to work. I am looking into the difference.

**Comment by canihavethisone** [comment]
fixed in v1.0.11
