### ISSUE TITLE
Chrony dependency missing for cis_2_2_1_3

### ISSUE THREAD

**Issue by canihavethisone** [fervidus/secure_linux_cis#15]
if chrony is selected as time_sync value, cis_2_2_1_3 fails to apply as there is no chrony resource listed in dependencies.  I have looked briefly at using aboe/chrony however this should be further checked as there are a few chrony modules to choose from (not all will work with an array time source for example).

aboe/chrony was removed on a previous merge when fixtures and metadata were made uniform - may have been my bad...

EDIT: it does appear in .fixtures but not in puppetfile or metadata

**Comment by bjvrielink** [comment]
I did add it in .fixtures, as at that moment my main goal was to make all tests pass. I was as curious as you are about this, but did not dive into the change history.
aboe/chrony matches the way cis_2_2_1_3 uses chrony, so I think that that dependency should be added back into the metadata.

Speaking of metadata: some module dependencies are a bit outdated, and at the moment Centos7 is not listed as a supported os...

**Comment by canihavethisone** [comment]
I am preparing another merge request to move the 'TMOUT=600' file_line from cis_5_4_4 to cis_5_4_5 (where it should be) and add 'readonly TMOUT' and 'export TMOUT' lines.  I will also add aboe/chrony to metadata as part of that merge - will be a day or so before I get this ready.

**Comment by canihavethisone** [comment]
I have made changes and created a pull request, however Travis is failing spec test that pass locally with PDK.....

**Comment by canihavethisone** [comment]
Pull request created
