### ISSUE TITLE
Please support more distributions, like Debian 9

### ISSUE THREAD

**Issue by bjvrielink** [fervidus/secure_linux_cis#18]
And before you reply 'wait, that's a lot of work', please look at https://github.com/bjvrielink/secure_linux_cis/tree/debian for an almost complete implementation I'm currently working on for debian9.
It is still work in progress:
- A dozen or so checks do not yet result in a passing grade in CIS-CAT
- I need to write spec tests for a few new classes
- More testing

I could use some input/feedback on how I wrote the code for Debian 9 support. I tried to re-use as much code as possible, and made any class that was RedHat specific also work on Debian(9). This resulted in many 'redhat7' classes included in 'debian9.pp'. Which looks weird, but works. Any thoughts on a better way of doing this?

**Comment by bryanjbelanger** [comment]
Wait!

That seems like a good idea.

I’ll take a look tonight.

Thanks,

Bryan Belanger | Principal Consultant

phone: +1 (248) 613-2538 | email: bryan@fervid.us <mailto:bryan@fervid.us>

**Comment by bjvrielink** [comment]
Keep in mind that the numbering of some of the checks are also different between distributions (see the comments in debian9.pp). Also, there is a "Distribution Independent Benchmark" that may be used for the 'common' section.
Either way, it is a lot of work moving (almost) all classes to a new naming scheme. I'm not against contributing time towards that work, as long as there is a consensus before I commit to it :)

**Comment by bryanjbelanger** [comment]
Created a new branch add_new_distributions. Will add a bunch of stuff today. Will have more time to clean it up week after next.

**Comment by bryanjbelanger** [comment]
@bjvrielink @dan-wittenberg @prolixalias @canihavethisone @prolixalias 

I have pushed a new branch here: https://github.com/fervidus/secure_linux_cis/tree/add_new_distributions

This is still rough and I need suggestions.

I have all the CIS rules broken down by common, os and os major version. They use class names describing the rule vs. the CIS number. (Many rules are common after all)

I renamed the current CIS class to their rule name.

IF this path is taken we likely need to change the class array in Hiera to something we are doing already so we can pass parameters to the classes. Also need to pass boolean value.

I am looking for comments at this point.

Thanks,

Bryan

**Comment by dan-wittenberg** [comment]
The only thing I don't care for is the renaming, I think it finds it harder
to find which one you are looking for.  Usually when I get reports of
non-compliance I get the number and maybe the name, but I think the
numbering makes that easier and faster to see them in order as well,
otherwise looks good so far!

Dan

**Comment by bryanjbelanger** [comment]
The names and numbers don't match up across OSs. Any ideas how we can keep numbering without redundant classes? Maybe have a numbered shell class that 'contains' the named class?

**Comment by dan-wittenberg** [comment]
Yeah I like that better, so at least when you look at the different ones
you can easily tell right where to go without having to go lookup something
else.

**Comment by bjvrielink** [comment]
Apologies for the lack of updates from my side the last few days. I've been busy...
I've just added a few more commits to my fork, including support for Ubuntu 18.04.

**Comment by canihavethisone** [comment]
@bjvrielink were you at Microsoft Ignite in Orlando last week?

**Comment by bjvrielink** [comment]
> @bjvrielink were you at Microsoft Ignite in Orlando last week?

I deny everything...

**Comment by bryanjbelanger** [comment]
HI @bjvrielink , what branch should I pull from to get Ubuntu stuff?

**Comment by bjvrielink** [comment]
Ubuntu18.04 is also in the Debian branch. Changes for Ubuntu were minimal, once Debian was done.
I think it needs rebasing to this repo's master, but should be trivial.

**Comment by canihavethisone** [comment]
> > @bjvrielink were you at Microsoft Ignite in Orlando last week?
> 
> I deny everything...

I think we sat at the same table in the meals hall for lunch, maybe Wednesday  I recognized your face and was trying to read your name badge but realized who you were after you left the table.  Would have been great to have a chat.

**Comment by bjvrielink** [comment]
Having a chat indeed would have been great, but the chance of running into me in Orlando is quite low. Not only because I live in the Netherlands, but also because my profile picture is a little outdated and lacks the facial hair I currently have.

**Comment by canihavethisone** [comment]
> Having a chat indeed would have been great, but the chance of running into me in Orlando is quite low. Not only because I live in the Netherlands, but also because my profile picture is a little outdated and lacks the facial hair I currently have.

It must have been your doppelganger.  :)

**Comment by bryanjbelanger** [comment]
@bjvrielink @dan-wittenberg  @prolixalias  @canihavethisone 



I have pushed a new branch here: https://github.com/fervidus/secure_linux_cis/tree/add_new_distributions

Please review.

**Comment by canihavethisone** [comment]
@bryanjbelanger that layout conceptually looks awesome.  I had a feeling that module-level hiera could be used here.  I won't get to do any live testing with it for a few days however due to commitments (I like to do actual puppet runs, see if it breaks then run Nessus against the host).

One further thought is that all the shared profiles be renamed to just secure_linux_cis to make them version agnostic and avoid duplication.  These base, or shared profiles would not contain any thing which is not common across all linux releases, and only uncommon settings would be in the release directories.  This to me seems like the best way to refactor the module and make it ready for any/all releases.

**Comment by bjvrielink** [comment]
@bryanjbelanger great work!

With this huge change, it of course requires quite a bit testing. I'll try to make some time to help with this. However, once you're confident it's as good as the old code for RedHat/Centos7, I'd love to see a 2.0 version :)

**Comment by bjvrielink** [comment]
Did some testing on a Debian9 system. Made it to work (see my #25 )
Note that some older distributions like el6 require a lot of work before they can be used.

**Comment by abuxton** [comment]
I'd like to see the facts represent the related cis_benchmark in their names, or indeed one larger structured fact that shows pass/fail of the status of the benchmarks for reporting purposes
something akin to https://github.com/ipcrm/ipcrm-demo_cis/blob/master/lib/facter/cis_redhat.rb 
or even
```
 # 1.1.1.1 Ensure mounting of cramfs filesystems is disabled (Scored)
  results["1"]["1"]["1"]["1"] = {
    "title"  => "Ensure mounting of cramfs filesystems is disabled",
    "scored" => true,
    "level"  => { "server" => "1", "workstation" => "1" },
    "result" => "pass"
  }
  modprobe = Facter::Core::Execution.exec('/usr/sbin/modprobe -n -v cramfs')
  lsmod = Facter::Core::Execution.exec('/usr/sbin/lsmod | /usr/bin/grep "cramfs"')
  if ( modprobe != "install /bin/true" || lsmod != "" )
    results["1"]["1"]["1"]["1"]["result"] = "fail"
  end
```

**Comment by bjvrielink** [comment]
@abuxton At the moment the facts are more used as helper functions, not as pass/fail facts. Some facts are used by more than one benchmark item.
Also, CIS is highly inconsistent in numbering of their benchmarks between distributions. 1.1.1.1 for example is about cramfs for Centos7, but about freevxfs for Debian9 (which is 1.1.1.2 for Centos7).

**Comment by canihavethisone** [comment]
I'm currently testing the 2.0.6 release, however a few questions/notes:
1. How do you opt in for the level 2 settings that have been commented out?  One method is for an implementer to duplicate the rules in environment or wrapping module hiera, however it would be good to have a way to opt for L1, L2 or both via a param
2. The current version on the forge is 2.0.5, I am unsure if this is a publishing issue of if 2.0.6 didn't make it there yet
3. the readme will need considerable rewriting with this new version, but I'm sure I am stating the obvious there.

I have not tested releases other than Centos 7 as yet, and always verify the results with Nessus, bu I have to say that this refactored version 2x is looking REALLY good Brian - well done and a huge thank you for all the time and effort that you and other contributors have put into the is module.  It's absolutely awesome.

**Comment by bryanjbelanger** [comment]
The L2 thing is a UX decision. I am open to suggestions. Some maybes:

1) Let users add them one by one in the include_rules array in the control
repo.
2) Add something like 'All' to the profile_type parameter.
3) Something else...?

2.0.6 not packaged yet.

The README needs a rewrite. Other things in the classes need to be
documented too. I am still working on SLES and Ubuntu profiles.

Also, some classes in RHEL 8 and Debian 9 need to be implemented.

Thanks,

Bryan

**Comment by canihavethisone** [comment]
I think that the option should be exposed and not require repo (env) level hiera overrides.

My first thought is to handle it be:
i) exposing a new param of
  `Optional[Array[Integer[1, 2]]]  $hardening_level = [1],`
or  `Optional[Array[Enum[1, 2]]]  $hardening_level = [1],`
(I haven't yet tested if that works or which is more appropriate)

alternatively the $profile_type param could be extended but that would logically include L1 when L2 selected (not sure if there is a use case for L2 only?)

ii) changing the hiera keys to 
  `secure_linux_cis::workstation_rules_level1:
  secure_linux_cis::workstation_rules_level2:
  secure_linux_cis::server_rules_level1:
  secure_linux_cis::server_rules_level2:`

iii) refactoring the logic in init.pp that builds the $base_rules param to account for the above

**Comment by canihavethisone** [comment]
@bryanjbelanger, delighted to see the latest release - I hope to do some testing later this week.
Re the commenting out of level 2 hardening, do you intend to separate then out and allow them to be enforced with a param set to true (as per the above post)?  The only other way I can think of for an end user would be to duplicate the hiera data at the environment level and remove #'s.

**Comment by bryanjbelanger** [comment]
A cis_level parameter that accepts a 1 or 2 is best.

Default it in common.yaml.

Do you have an account in Puppet Community Slack?

Thanks,

Bryan

Sent from my iPhone

On Feb 16, 2020, at 4:51 AM, canihavethisone <notifications@github.com> wrote:

﻿

@bryanjbelanger<https://github.com/bryanjbelanger>, delighted to see the latest release - I hope to do some testing later this week.
Re the commenting out of level 2 hardening, do you intend to separate then out and allow them to be enforced with a param set to true (as per the above post)? The only other way I can think of for an end user would be to duplicate the hiera data at the environment level and remove #'s.

**Comment by bryanjbelanger** [comment]
@prolixalias your thoughts?

**Comment by prolixalias** [comment]
@bryanjbelanger -- I got @canihavethisone 's [suggestion](https://github.com/fervidus/secure_linux_cis/issues/18#issuecomment-569468085) implemented with minor modifications. Result looks like the example(s). Testing today... Once done, I'll mark #19 closed. Thanks for the input and contributions everyone!

**Comment by bjvrielink** [comment]
Closing this issue
