### ISSUE TITLE
add support for centos 8 / rhel 8

### ISSUE THREAD

**Issue by canihavethisone** [fervidus/secure_linux_cis#20]
cis have recently published the benchmarks for centos 8 & rhel 8.  I have just downloaded and will look at the changelogs tonight.  My preference is to get centos in first.

Would be great to get this into the module.

**Comment by canihavethisone** [comment]
There is no changelog showing the differences between the Centos7 and 8 benchmarks in the CIS pdf.  Therefore the differences will need to be manually compared.

My thought is to create a new parent class centos8.pp, which will include the centos7 subclasses which are the same for 8 and also the changes or additions that will be stored in a centos8 folder.

Does anyone have a different idea?  One downside I can see is that we will effectively be referencing an earlier version for most of the new parent class, however this will avoid duplication.

**Comment by bjvrielink** [comment]
For the Debian9 and Ubuntu18.04 support, I've re-used as much modules as possible. New or completely different benchmarks I've put into a manifests/debian9 folder, but if only minor changes (like e.g. the name of a package or file) were needed to make it work, I've adapted the existing redhat7 class with a case statement.

**Comment by canihavethisone** [comment]
ok, leave it with me.  It may take a few weeks however.
