### ISSUE TITLE
rule ensure_nftables_is_not_enabled missing

### ISSUE THREAD

**Issue by johan-bergmans** [fervidus/secure_linux_cis#32]
Dear, 

In rhel8/cis_3_4_2_3.pp there if referred to the class :secure_linux_cis::rules::ensure_nftables_is_not_enabled, which is not existing. 

Kind regards 
Johan

**Comment by bjvrielink** [comment]
Looks like this is fixed in commit a4a1f6f8f4abffd8fdb3ea8b2896cc91fe8954d2?

**Comment by johan-bergmans** [comment]
bjvrielink, 

indeed is fixed in that commit. 

Thanks!
