### ISSUE TITLE
Please do not reboot systems unless this is requested

### ISSUE THREAD

**Issue by bjvrielink** [fervidus/secure_linux_cis#33]
There is a parameter auto_restart that I'd *really* want to be off, but even if it was off, the parameter is not used anyway.

Simply upgrading the module from 1.x to 2.x would mean *all* our servers would reboot, as for instance audit rules have slightly changed. This just scared the shit out of me.

Please please please do not default to rebooting systems!

**Comment by bryanjbelanger** [comment]
Come on! YOLO!

Ok, let me look at it...

**Comment by bjvrielink** [comment]
See #34

**Comment by bjvrielink** [comment]
For now, "puppet config set skip_tags reboot" as a workaround...

**Comment by bjvrielink** [comment]
Thank you
