### ISSUE TITLE
Module dependency is broken.

### ISSUE THREAD

**Issue by ajaynz** [fervidus/secure_linux_cis#63]
I can't seem to install the module as the module dependency is broken:

`[centos@puppet ~]$ puppet module install fervid-secure_linux_cis --version 2.1.16
Notice: Preparing to install into /home/centos/.puppetlabs/etc/code/modules ...
Notice: Downloading from https://forgeapi.puppet.com ...
Error: Could not install module 'fervid-secure_linux_cis' (???)
  No version of 'fervid-secure_linux_cis' can satisfy all dependencies
    Use `puppet module install --ignore-dependencies` to install only this module`

**Comment by bjvrielink** [comment]
Puppet modules (may) have dependencies on specific versions of other modules, usually on a range of versions up to the next major version. In the case of the secure_linux_cis module, it looks like there are newer versions of puppet/logrotate and puppet/cron that are not (yet) supported by this module.

If possible, can you downgrade puppet/cron to 1.3.1 and puppet/logrotate to 4.0.0 and see if that allows you to install this module?
If that is not an option, can you then at least provide a list of installed modules and their versions (puppet module list --tree)?
