### ISSUE TITLE
Setting boot password through module doesn't satisfy boot password compliance check

### ISSUE THREAD

**Issue by mikerenfro** [fervidus/secure_linux_cis#76]
So in the RHEL 7 CIS, version 2.2.0, the standard checks if `grep "^GRUB2_PASSWORD" /boot/grub2/grub.cfg` returns anything. `lib/facter/grub_pass.rb` checks for that in `/boot/grub/*.cfg`, but the `grub_user` resource in `manifests/rules/ensure_bootloader_password_is_set.pp` results in a line

```
password_pbkdf2 root grub.pbkdf2....
```

in `/boot/grub2/grub.cfg`, causing the `grub_pass` fact to always flag for a missing password.

The simplest fix would be to adjust the grep in the fact code, but I figured I'd get feedback on this before submitting a PR. The Debian section of the fact may also need similar changes, but I haven't tested this on a Debian system to know for certain.

**Comment by bjvrielink** [comment]
I know (from some painful experiences) that there are differences between the different distributions on how exactly they handle Grub2 passwords. I do intend to look into this and #75 on different distributions, but need to find some time for it.

**Comment by bryanjbelanger** [comment]
Fixed in 2.0.18
