### ISSUE TITLE
cis_1_6_1_1 update in v 1.0.7 appears to brick VM

### ISSUE THREAD

**Issue by canihavethisone** [fervidus/secure_linux_cis#8]
Steps to reproduce:
1. build a standard BIOS minimal CentOS7 VM (eg in VMware Workstation)
2. apply this module 
3. reboot

boot error:
Warning: /dev/mapper/centos_{hostname}-root does not exist
Warning: /dev/vg0/root does not exist
Warning: /dev/vg0/swap does not exist

Setting this class to enforced => false avoids the issue.

This issue has also been branched into 1.0.8.

I will investigate further however any thoughts appreciated.  Rolling this file back to release 1.0.5 version an option?

**Comment by canihavethisone** [comment]
Upon further investigation, the issue appears to be changing the default Centos build line in /etc/default/grub from:
GRUB_CMDLINE_LINUX="crashkernel=auto rd.lvm.lv=centos/root rd.lvm.lv=centos/swap rhgb quiet audit=1"

to 
GRUB_CMDLINE_LINUX="crashkernel=auto rd.lvm.lv=vg0/root rd.lvm.lv=vg0/swap rhgb quiet audit=1"

As I am not a RedHat user (just Centos here), do you have any suggestions on a version agnostic replacement for this line?  Or should it just be removed?

**Comment by dan-wittenberg** [comment]
I actually rewrote all the grub handling last night, I can try and get my
latest changes pushed up, that might resolve your issue. I'll also quick
test on a centos vm as well.

Dan

**Comment by canihavethisone** [comment]
OK great!  Note the update the my comment that the lv name shouldn't be assumed as it could be anything.

Can you pls pull the current master into your branch before pushing, so the 1.0.8 changes are preserved?

Cheers.

**Comment by dan-wittenberg** [comment]
Well, got everything working well, went to rebase and somehow wiped out all
my changes from the last few days, so hours of work gone...it will be
awhile before I get time to fix it all again but I'll try.

**Comment by canihavethisone** [comment]
this can be closed
