### ISSUE TITLE
include_rules and exclude_rules disabled in module init.pp

### ISSUE THREAD

**Issue by jnathan-ias** [fervidus/secure_linux_cis#97]
Hello!

I've noticed that `include_rules` and `exclude_rules` values have been [commented out](https://github.com/fervidus/secure_linux_cis/blob/main/manifests/init.pp#L172) in the modules `init.pp`.

In previous releases this was enabled and allowed users to use hiera.

Was this an intended change to interfacing with the module? 

Thankyou for your time and the work you have done on this repo!

**Comment by bryanjbelanger** [comment]
I’ll be adding them back in. Hopefully before Monday.

On Nov 17, 2022, at 4:15 PM, jnathan-ias ***@***.***> wrote:



Hello!

I've noticed that include_rules and exclude_rules values have been commented out<https://github.com/fervidus/secure_linux_cis/blob/main/manifests/init.pp#L172> in the modules init.pp.

In previous releases this was enabled and allowed users to use hiera.

Was this an intended change to interfacing with the module?

  *   Thankyou for your time and the work you have done on this.

**Comment by jnathan-ias** [comment]
Cheers, thankyou for the reply.
